# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 92a7ea4b97a41522b922ec8bdab798fe958e0c5851d825c701539abdc4fc636d1f41d6acbdd3bb20ac81da0e3485ec7537d30e24136c3190a9ddcbd8259d2f47

test:
  secret_key_base: 60f753f04fbc3156bcda65e1f8dbbdd46e6977984ad19854c82b6bbe014e01d2be63f7fbad30698b6752ef908a6be73a3a3a5e4d0622070b81bee7c008ff2aa8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
